### ISSUE TITLE
Error executing command.

### ISSUE THREAD

**Issue by 2ndAery** [NullPointer-Nico/WarpSystem#2]
When trying to warp console spits out this error.

`[FATAL] Unhandled exception executing command "w spawn" in w: java.lang.NullPointerException
        at de.nico.warpsystem.WarpSystem.getWarp(WarpSystem.java:90)
        at de.nico.warpsystem.commands.WarpCommand.execute(WarpCommand.java:27)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:761)
        at cn.nukkit.Player.handleDataPacket(Player.java:2750)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:123)
        at cn.nukkit.network.Network.processInterfaces(Network.java:165)
        at cn.nukkit.Server.tick(Server.java:1157)
        at cn.nukkit.Server.tickProcessor(Server.java:930)
        at cn.nukkit.Server.start(Server.java:898)
        at cn.nukkit.Server.<init>(Server.java:582)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)

17:37:42 [ERROR] Throwing
java.lang.NullPointerException: null
        at de.nico.warpsystem.WarpSystem.getWarp(WarpSystem.java:90) ~[?:?]
        at de.nico.warpsystem.commands.WarpCommand.execute(WarpCommand.java:27) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:761) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:123) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:165) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:930) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:898) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]`

**Comment by NullPointer-Nico-zz** [comment]
Its fixxed download the newest version from cloudburst.
